# Generated by Django 3.0.8 on 2020-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images/mainpage/projects')),
                ('title', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True, max_length=300)),
                ('live_link', models.URLField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('tag1', models.CharField(choices=[('machinelearning', 'machinelearning'), ('webdevelopment', 'webdevelopment'), ('electronics', 'electronics')], max_length=50)),
                ('tag2', models.CharField(blank=True, choices=[('machinelearning', 'machinelearning'), ('webdevelopment', 'webdevelopment'), ('electronics', 'electronics')], max_length=50)),
                ('tag3', models.CharField(blank=True, choices=[('machinelearning', 'machinelearning'), ('webdevelopment', 'webdevelopment'), ('electronics', 'electronics')], max_length=50)),
            ],
        ),
    ]
